# Generated by Django 4.0.4 on 2022-04-20 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=465)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('email_from', models.CharField(max_length=20)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('sent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=500)),
                ('cc', models.CharField(blank=True, max_length=500, null=True)),
                ('bcc', models.CharField(blank=True, max_length=500, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=200, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mailbox')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.template')),
            ],
        ),
    ]
